name: nsc2026
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - aws-c-auth=0.9.3=hdff831d_0
  - aws-c-cal=0.9.13=hea39f9f_1
  - aws-c-common=0.12.6=h8616949_0
  - aws-c-compression=0.3.1=h901532c_9
  - aws-c-event-stream=0.5.7=ha05da6a_1
  - aws-c-http=0.10.7=h924c446_5
  - aws-c-io=0.23.3=hf559bb5_5
  - aws-c-mqtt=0.13.3=ha72ff4e_11
  - aws-c-s3=0.11.3=he30762a_1
  - aws-c-sdkutils=0.2.4=h901532c_4
  - aws-checksums=0.2.7=h901532c_5
  - aws-crt-cpp=0.35.4=h7484968_0
  - aws-sdk-cpp=1.11.606=h386ebac_10
  - azure-core-cpp=1.16.1=he2a98a9_0
  - azure-identity-cpp=1.13.2=h0e8e1c8_1
  - azure-storage-blobs-cpp=12.16.0=ha4e89a6_0
  - azure-storage-common-cpp=12.12.0=h2a5eb39_0
  - azure-storage-files-datalake-cpp=12.14.0=h7f37a48_0
  - backports.zstd=1.3.0=py311hdc67420_0
  - bokeh=3.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=hf139dec_1
  - brotli-bin=1.2.0=h8616949_1
  - brotli-python=1.2.0=py311h7e844b6_1
  - bzip2=1.0.8=h500dc9f_8
  - c-ares=1.34.6=hb5e19a0_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py311h9d13916_4
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.1.0=py311hf197a57_1
  - dask=2026.1.2=pyhcf101f3_0
  - dask-core=2026.1.2=pyhcf101f3_0
  - distributed=2026.1.2=pyhcf101f3_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - fonttools=4.61.1=py311he13f9b5_0
  - freetype=2.14.1=h694c41f_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - gflags=2.2.2=hac325c4_1005
  - glog=0.7.1=h2790a97_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - kiwisolver=1.4.9=py311h591569d_2
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.18=h90db99b_0
  - lerc=4.0.0=hcca01a6_1
  - libabseil=20250512.1=cxx17_hfc00f1c_0
  - libarrow=23.0.0=h8071b21_1_cpu
  - libarrow-acero=23.0.0=h9737151_1_cpu
  - libarrow-compute=23.0.0=hc26cc94_1_cpu
  - libarrow-dataset=23.0.0=h9737151_1_cpu
  - libarrow-substrait=23.0.0=h7f2e36e_1_cpu
  - libblas=3.11.0=5_he492b99_openblas
  - libbrotlicommon=1.2.0=h8616949_1
  - libbrotlidec=1.2.0=h8616949_1
  - libbrotlienc=1.2.0=h8616949_1
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.18.0=h9348e2b_0
  - libcxx=21.1.8=h4fb565c_2
  - libdeflate=1.25=h517ebb2_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libexpat=2.7.3=heffb93a_0
  - libffi=3.5.2=hd1f9c09_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgcc=15.2.0=h08519bb_17
  - libgfortran=15.2.0=h7e5c614_17
  - libgfortran5=15.2.0=hd16e46c_17
  - libgoogle-cloud=2.39.0=hed66dea_0
  - libgoogle-cloud-storage=2.39.0=h8ac052b_0
  - libgrpc=1.73.1=h451496d_1
  - libiconv=1.18=h57a12c2_2
  - libjpeg-turbo=3.1.2=h8616949_0
  - liblapack=3.11.0=5_h859234e_openblas
  - liblzma=5.8.2=h11316ed_0
  - libnghttp2=1.67.0=h3338091_0
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libopentelemetry-cpp=1.21.0=h7d3f41d_1
  - libopentelemetry-cpp-headers=1.21.0=h694c41f_1
  - libparquet=23.0.0=ha0d2768_1_cpu
  - libpng=1.6.54=h07817ec_0
  - libprotobuf=6.31.1=hcc66ac3_4
  - libre2-11=2025.11.05=h554ac88_0
  - libsqlite=3.51.2=hb99441e_0
  - libssh2=1.11.1=hed3591d_0
  - libthrift=0.22.0=h687e942_1
  - libtiff=4.7.1=ha0a348c_1
  - libutf8proc=2.11.3=hc282952_0
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.15.1=h745d5cb_1
  - libxml2-16=2.15.1=hd57b93d_1
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.8=h472b3d1_0
  - llvmlite=0.46.0=py311hb26b958_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py311h14c9969_1
  - lz4-c=1.10.0=h240833e_1
  - markupsafe=3.0.3=py311he13f9b5_0
  - matplotlib=3.10.8=py311h6eed73b_0
  - matplotlib-base=3.10.8=py311h48d7e91_0
  - msgpack-python=1.1.2=py311haec20ae_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.16.0=pyhcf101f3_0
  - ncurses=6.5=h0622a9a_3
  - nlohmann_json=3.12.0=h06076ce_1
  - numba=0.63.1=py311hfe9595b_0
  - numpy=2.3.5=py311h3402b43_1
  - openjpeg=2.5.4=h87e8dc5_0
  - openssl=3.6.1=hb6871ef_1
  - orc=2.2.2=h3073fbf_0
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py311hfbd1ee4_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pillow=12.1.0=py311h127dec8_0
  - pip=26.0.1=pyh8b19718_0
  - pluggy=1.6.0=pyhf9edf01_1
  - prometheus-cpp=1.3.0=h7802330_0
  - psutil=7.2.2=py311ha332486_0
  - pthread-stubs=0.4=h00291cd_1002
  - pyarrow=23.0.0=py311h6eed73b_0
  - pyarrow-core=23.0.0=py311hb7850dc_0_cpu
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.2=pyhcf101f3_0
  - python=3.11.14=h74c2667_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - pyyaml=6.0.3=py311h53ebfaf_1
  - qhull=2020.2=h3c5361c_5
  - re2=2025.11.05=h7df6414_0
  - readline=8.3=h68b038d_0
  - scipy=1.17.0=py311h553d447_1
  - setuptools=80.10.2=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h01f5ddf_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - tblib=3.2.2=pyhcf101f3_0
  - tk=8.6.13=h7142dee_3
  - tomli=2.4.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py311ha2bb86f_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py311hf197a57_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h4132b18_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hd23fc13_2
  - zlib-ng=2.3.3=h8bce59a_1
  - zstd=1.5.7=h3eecb57_6

prefix: "/Users/kimnielsen/miniforge3/envs/nsc2026"